circle = [[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'st', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'b1', 'st', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['st', 'b1', 'b1', 'h1', 'nt', 'nt', 'nt'], ['nt', 'st', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'nt', 'nt', 'nt'], ['st', 'b1', 'b1', 'b1', 'nt', 'nt', 'nt'], ['nt', 'st', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'st', 'nt', 'nt', 'nt', 'nt', 'nt'], ['st', 'b1', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'b1', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'b1', 'b1', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'st', 'nt', 'nt', 'nt', 'nt', 'nt'], ['st', 'b1', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'b1', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'b1', 'b1', 'b1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'b1', 'b1', 't1', 'st', 'nt', 'nt'], ['nt', 'b1', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'b1', 'b1', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'b1', 't1', 'nt', 'st', 'nt', 'nt'], ['nt', 'b1', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'b1', 'b1', 'b1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'st', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'st', 'b1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'b1', 'b1', 'st'], ['nt', 'nt', 'nt', 'nt', 'nt', 'st', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'b1', 'b1', 'b1', 'st'], ['nt', 'nt', 'nt', 'nt', 'nt', 'st', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'st', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'b1', 'st'], ['nt', 'nt', 'nt', 'nt', 'nt', 'b1', 'nt'], ['nt', 'nt', 'nt', 'h1', 'b1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'st', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'b1', 'st'], ['nt', 'nt', 'nt', 'h1', 'nt', 'b1', 'nt'], ['nt', 'nt', 'nt', 'b1', 'b1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'st', 't1', 'b1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'b1', 'nt'], ['nt', 'nt', 'nt', 'h1', 'b1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']], 
[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'st', 'nt', 'nt', 'nt'], ['nt', 'nt', 'st', 'nt', 't1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'h1', 'nt', 'b1', 'nt'], ['nt', 'nt', 'nt', 'b1', 'b1', 'b1', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']]] 

left1 = [[['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'st', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']]]

left2 = [[['nt', 'st', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'st', 'nt', 'h1', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt'], ['nt', 'nt', 'nt', 'nt', 'nt', 'nt', 'nt']]]

